### ISSUE TITLE
No module named 'subtrie'

### ISSUE THREAD

**Issue by icaropires** [emitter-io/python#14] opened 2019-06-06 23:18 UTC
## Problem

I installed the package version 2.0.0 and get this error when trying using:

![image](https://user-images.githubusercontent.com/18473249/59072147-dbc3eb00-8897-11e9-8452-a2094852cb5d.png)

In version 1.3.0 I can import it or using the source code. The problem is with the package at version 2.0.0

## Details

Package version: 2.0.0
SO: Manjaro, Linux
Python version: 3.7.3

**Comment by Florimond** [comment] 2019-06-07 07:38
Indeed, the issue is already fixed in the sources, the pip package will be updated tonight.

**Comment by Florimond** [comment] 2019-06-08 12:55
@icaropires It should work now.

**Comment by icaropires** [comment] 2019-06-08 14:15
Cool! Now it's working @Florimond. Thank you!

**Closed as completed** 2019-06-13 03:24 UTC
